export const VEC_ICON_NAME = {
    SIDEBAR_HOME_ICON: 'SidebarHomeIcon',
    DUMMY_LOGO: 'DummyLogo',
    SIDEBAR_NEW_JOINER: 'SidebarNewJoiner',
    SIDEBAR_TODAYS_TASKS: 'SidebarTodaysTasks',
    SIDEBAR_MONTHLY_SCHEDULE: 'SidebarMonthlySchedule',
    SIDEBAR_MY_ACCOUNT: 'SidebarMyAccount',
    SIDEBAR_CONTACT_US_ICON: 'SidebarContactUsIcons',
    SIDEBAR_FAQS_ICON: 'SidebarFaqsIcon',
    SIDEBAR_EXPAND_DOT_ICON: 'SidebarExpandDotIcon',
    HEADER_BACK_ARROW: 'HeaderBackArrow',
    HEADER_FILTER_ICON: 'HeaderFilterIcon',
    HEADER_NOTIFICATION_ICON: 'HeaderNotificationIcon',
    BREADCRUMB_HOME_ICON: 'BreadcrumbHomeIcon',
    CHECKBOX_ICON: 'CheckBoxIcon',
    CHECKBOX_DASH_ICON: 'CheckboxDashIcon',
    STEP_DONE_ICON: 'StepDoneIcon',
    ALERT_ROUNDED_ICON: 'AlertRoundedIcon',
    FILTER_LINES_ICON: 'FilterLineIcons',
    FEATHER_UPLOAD_CLOUD_ICON: 'CloudIcon',
    PLUS_ICON: 'PlusIcon',
    ADD_NEW_ICON: 'AddNewIcon',
    ARROW_DOWN_ICON: 'ArrowDownIcon',
    FILE_UPLOADING_ICON: 'FileUploadingIcon',
    ICON_DROPDOWN_CARET: 'IconDropdownCaret',
    RADIO_BUTTON_ICON: 'RadioButtonIcon',
    FAX_ICON: 'FaxIcon',
    EMAIL_ICON: 'EmailIcon',
    WAITING_IMAGE: 'WaitingImage',
    GREEN_ELLIPSE: 'GreenEllipse',
    CROSS_ICON: 'CrossIcon',
    CORRECT_ICON: 'CorrectIcon',
    INTERVIEW_ICON: 'InterviewIcon',
    FINAL_RESULT_IMAGE: 'FinalResultImage',
    SECTION_ICON: 'SectionIcon',
    ELLIPSE_GREY_ICON: 'EllipseGreyIcon',
    VECTOR_ICON: 'VectorIcon',
    ICON_LEFT: 'IconLeft',
    CALL_ICON: 'CallIcon',
    MAIL_OUTLINE: 'EmailsIcon',
    LOCATION_ICON: 'LocationIcon',
    LOCATION_ICON_2: 'LocationIcon2',
    DESCRIPTION_ICON: 'DescriptionIcon',
    CALENDER_ICON: 'CalenderIcon',
    BOOKMARK_ICON: 'BookmarkIcon',
    BUILDING: 'Building',
    DOLLAR_ICON: 'DollarIcon',
    ARROW_DOWN_ICON_SIDEBAR: "ArrowDownIconSidebar",
    LOCATION_ICON_3: "LocationIcon3",
    ICON_RIGHT: "IconRight",
    ICON_LEFT_2: "IconLeft2",
    ARROW_RIGHT_ICON: "ArrowRightIcon",
    PATIENT_ONBOARDING: "PatientOnBoarding",
    JOB_APPLICATION_ICON: "JobApplicationIcon",
    PENDING_CLAIMS: "PendingClaims",
    UP_ARROW: "UpArrow",
    EPISODE_ICON: "EpisodeIcon",
    SCHEDULE_ICON: "ScheduleIcon",
    TASK_LIST_ICON: "TaskListIcon",
    PROGRESS_NOTES_ICON: "ProgressNotesIcon",
    MEDICATION_ICON: "MedicationIcon",
    VITAL_SIGNS_ICON: "VitalSignIcon",
    CLAIMS_ICON: "ClaimsIcon",
    PACKET_ICON: "PacketIcon",
    Inbound_Icon:"InboundIcon",
    Outbound_Icon:"OutboundIcon",
    Inbox:"Inbox",
    Favorites:"Favorites",
    Send:"Send",
    Drafts:"Drafts",
    Trash:"Trash",
    TrippleDot:"TrippleDot",
    Star:"Star",
    SearchIcon:"SearchIcon",
    GreenDot:"GreenDot",
    ArrowLeftIcon:"ArrowLeftIcon",
    EmailRow:"EmailRow",
    OpenIcon:"OpenIcon",
    PrinterIcon:"PrinterIcon",
    ReplyIcon:"ReplyIcon",
    SideNavDeleteIcon:"SideNavDeleteIcon",
    SideNavInfoIcon:"SideNavInfoIcon",
    Avtar:"Avtar",
    ArrowDown:"ArrowDown",
    ForwardIcon:"ForwardIcon",
    PlusColorIcon:"PlusColorIcon",
    RightArrow:"RightArrow",
    SearchWhiteIcon:"SearchWhiteIcon",
    InfoOutlined:"InfoOutlined",
    SearchTransparent:"SearchTransparent",
    PrinterWhite:"PrinterWhite",
    DownloadList:"DownloadList",
    RedDot:"RedDot",
    InfoRedIcon:"InfoRedIcon",
    DollarBlue:"DollarBlue",
    DownloadBlue:"DownloadBlue",
    DownBlueArrow:"DownBlueArrow",
    SuccessGreenArrow:"SuccessGreenArrow",
    ArrowRightBlack:"ArrowRightBlack",
    EmailBoxIcon:"EmailBoxIcon",
    PrinterIconFilled:"PrinterIconFilled",
    SaveIcon: "SaveIcon",
    RefreshIcon: "RefreshIcon",
    COPY_ICON: "CopyIcon",
    CAMERA_ICON:'CameraIcon'
};
